name: 'Standard JS Action'
description: 'Professional JS Action setup'
inputs:
  who-to-greet:
    description: 'Name to greet'
    required: true
    default: 'DevEx Engineer'
outputs:
  time:
    description: 'The time of the greeting'
runs:
  using: 'node20'
  main: 'dist/index.js' # We point to the bundled file, not the source