name: anchors-and-aliases
on: [workflow_dispatch] 

jobs:
  job1:
    runs-on: ubuntu-latest
    env: &env_vars # Define the anchor on first use
      NODE_ENV: production
      MY_JOB_STEP_ENV_VAR: ${{github.run_id}}
    steps:
      - run: echo "Using production NODE_ENV-> $NODE_ENV and MY_JOB_STEP_ENV_VAR->$MY_JOB_STEP_ENV_VAR"

  job2:
    runs-on: ubuntu-latest
    env: *env_vars # Reuse the environment variables
    steps:
      - run: echo "Same environment variables here $MY_JOB_STEP_ENV_VAR and $MY_JOB_STEP_ENV_VAR"