name: expressions
on: [workflow_dispatch] 

env:
    MY_JOB_ENV_VAR: ${{github.job}}

jobs:
  expressions-static:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd 

        - name: echo "expressions "
          run: |
            echo "This is a static expression test."
            echo "Event Name: ${{ github.event_name }}"
            echo "Current Workflow: ${{ github.workflow }}"
            echo "Event Name: ${{ github.event_name }}"
            echo "Repository: ${{ github.repository }}"
            echo "Job name: $MY_JOB_ENV_VAR"
        
        - name: Static Expression Test
          if: ${{ github.event_name == 'push' }} # This will always be false in a workflow_dispatch, but it's just for demonstration
          run: |
            echo "This is a static expression test."
            echo "Current Workflow: ${{ github.workflow }}"
            echo "Event Name: ${{ github.event_name }}"
            echo "Repository: ${{ github.repository }}"
            echo "Job name: $MY_JOB_ENV_VAR"

        - name: Case Insensitive Test
          run: |
            echo "Are equal: [[ "${{GITHUB.REF}}" == "${{github.ref}}" ]]"
        
        - name: Implicit strings
          if: github.event_name == 'workflow_dispatch'  # This will be true, but it's just for demonstration
          run: |
                echo "You don't need to use brackets and quotes for simple expressions like this."
                echo "Current Workflow: ${{ github.workflow }}"
                echo "Event Name: ${{ github.event_name }}"
                echo "Repository: ${{ github.repository }}"