name: matrices

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # 🧪 Don't stop if one OS fails; we want full results
      max-parallel: 2   # 💰 Save concurrency for other developers
      matrix:
        os: [ubuntu-latest, windows-2025]
        node: [18, 20, 22]
        # 1. Exclude a problematic combination
        exclude:
          - os: windows-2025
            node: 18
        # 2. Add an "Extra" job that isn't in the standard product
        include:
          - os: ubuntu-latest
            node: 20
            experimental: true # This variable only exists for this specific job

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: ${{ matrix.node }}
      - name: Experimental Check
        if: ${{ matrix.experimental == true }}
        run: echo "Running special e53b83947a5a98c8d113130e565377fae1a50d02fxperimental tests..."

  build-sim:
    runs-on: ${{ matrix.my_custom_os }} # Accessing a custom key
    strategy:
      matrix:
        # You define the keys here:
        my_custom_os: [ubuntu-latest, windows-latest]
        foo: [18, 20]
        
    steps:
      - run: echo "Running on ${{ matrix.my_custom_os }} with Node ${{ matrix.foo }}"