name: metadata-security
on: [workflow_dispatch] 

jobs:
  metadata-test:
    runs-on: ubuntu-latest
    steps:
      # Pinned to SHA for security
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd 
      
      - name: Print Metadata
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Triggering Actor: ${{ github.actor }}"
          echo "Runner OS: ${{ runner.os }}"