name: node build
on:
  workflow_call:
    outputs:
      artifact-name:
        description: "The name of the uploaded reports"
        value: ${{ jobs.build.outputs.artifact-name }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.set-name.outputs.name }}
    steps:
      - id: set-name
        run: echo "name=reports-${{ github.run_id }}" >> $GITHUB_OUTPUT
        
      - name: Checkout Code
        # actions/checkout@v4
        uses: actions/checkout@v1

      - name: Run Smart Setup
        # Use the SHA pinned by Dependabot
        uses: cert-labs-hq/automations-repo/.github/actions/setup@v1
        with:
          node-version: '24'

      - name: Build
        run: npm run build

    # Simulate generating reports (SAST, SCA, Tests) 
      - name: Generate Reports. 
        run: |
            mkdir -p reports
            echo "SAST: No vulnerabilities found" > reports/sast.txt
            echo "SCA: 0 high risks" > reports/sca.txt

      - name: Upload Compliance Artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7 pinned
        with:
            name: reports-${{ github.run_id }}
            path: reports/
            retention-days: 1 # Keep it short for ephemeral reports