name: Test Version Action
on: [workflow_dispatch] 

jobs:
  test-database:
    runs-on: ubuntu-latest
    
    # These services are sidecars to the job
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
        ports: 
          - 5432:5432
      redis:
        image: redis
        ports: 
          - 6379:6379

    steps:
      - name: Check Connectivity
        run: |
          # Install netcat to test TCP ports
          sudo apt-get update && sudo apt-get install -y netcat-openbsd
          
          # Test Postgres
          nc -zv localhost 5432
          
          # Test Redis
          nc -zv localhost 6379