name: Test Version Action
on: [workflow_dispatch] 

jobs:
  test-database:
    runs-on: ubuntu-latest
    
    # These services are sidecars to the job
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
      redis:
        image: redis

    steps:
      - name: Check Connectivity
        # Because we are in a 'job container', we use the service label as the host
        run: |
          apt-get update && apt-get install -y --no-install-recommends iputils-ping && rm -rf /var/lib/apt/lists/*
          ping -c 1 postgres
          ping -c 1 redis