name: Reusable workflow
on: 
    workflow_call:
      inputs:
        ref_name:
          description: 'The ref name to use as an environment variable'
          type: string
          required: true
          default: 'default-ref-name'


jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Mandatory for local actions
      - name: check secret
        run: |
          the_secret=${{ secrets.TOP_SECRET }}
          echo "The secret value is $the_secret" with ${#the_secret} letters
          echo "The ref name is ${{ inputs.ref_name }}"