name: secrets
on: workflow_dispatch # workflow_dispatch allows manual triggers in the UI

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
    - name: Masking Test
      env:
        MY_PWD: ${{ secrets.TEST_SECRET }}
      run: |
        # GitHub will catch this and show ***
        echo "My password is $MY_PWD" 
        # WARNING: This might show the encoded version!
        echo "Base64: $(echo -n $MY_PWD | base64)"