name: Test Version Action
on: [workflow_dispatch] # workflow_dispatch allows manual triggers in the UI

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Mandatory for local actions

      - name: Run our custom action
        id: versioning # You need an ID to capture outputs
        uses: ./.github/actions/get-version

      - name: Use the Output
        run: echo "The version created was ${{ steps.versioning.outputs.app-version }}"

      - name: debug context
        run: echo '${{ toJson(github) }}'
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: debug context
        run: echo '${{ toJson(github) }}'
  use-context-and-env:
    runs-on: ubuntu-2204  
    if: github.event_name == 'workflow_dispatch'
    env:
      MY_ENV_VAR: ${{github.event.ref_name}}
    steps:
      - name: print a variable
        run: |
          echo "this is a env variable : $MY_ENV_VAR"
  call-reusable-workflow:
    uses: ./.github/workflows/test-reusable-workflow.yml
    with:
      ref_name: 'test-ref'
      secrets: inherit
  