on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/node-build.yml # Nested call

  compliance:
    needs: build
    uses: ./.github/workflows/compliance-logic.yml # Nested call
    with:
      # Pass the output from the build to the compliance workflow
      report-artifact-name: ${{ needs.build.outputs.artifact-name }}