on:
  workflow_call:

jobs:
  run-compliance:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        # Call your centralized action
        - name: Run Drift Fixer
          uses: cert-labs-hq/automations-repo/.github/actions/drift-fixer@v1
          with:
            token: ${{ secrets.BOT_TOKEN }}

  build:
    uses: cert-labs-hq/automations-repo/.github/workflows/node-build.yml@v1 # Nested call

  compliance:
    needs: build
    uses: cert-labs-hq/automations-repo/.github/workflows/compliance-logic.yml@v1 # Nested call
    with:
      # Pass the output from the build to the compliance workflow
      report-artifact-name: ${{ needs.build.outputs.artifact-name }}  