on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
    secrets:
      BOT_TOKEN:
        required: true

jobs:
  run-compliance:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        # Call your centralized action
        - name: Run Drift Fixer
          uses: cert-labs-hq/automations-repo/.github/actions/drift-fixer@v1
          with:
            token: ${{ secrets.BOT_TOKEN }}
            repository: ${{ inputs.repo_name }} # Ensures it checks out the caller repo

  build:
    needs: run-compliance
    uses: cert-labs-hq/automations-repo/.github/workflows/node-build.yml@v1 # Nested call

  compliance:
    needs: build
    uses: cert-labs-hq/automations-repo/.github/workflows/compliance-logic.yml@v1 # Nested call
    with:
      # Pass the output from the build to the compliance workflow
      report-artifact-name: ${{ needs.build.outputs.artifact-name }}  