name: variables
on: [workflow_dispatch] # workflow_dispatch allows manual triggers in the UI

env:
  MY_GLOBAL_ENV_VAR: ${{github.repositoryUrl}}
  DAY_OF_WEEK: Monday

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Mandatory for local actions

      - name: Run our custom action
        id: versioning # You need an ID to capture outputs
        uses: ./.github/actions/get-version

      - name: Use the Output
        run: echo "The version created was ${{ steps.versioning.outputs.app-version }}"

      - name: debug context
        run: echo '${{ toJson(github) }}'
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: debug context
        run: echo '${{ toJson(github) }}'
  use-context-and-env:
    runs-on: ubuntu-22.04  
    needs: modify-global-env-var
    env:
      MY_JOB_ENV_VAR: ${{github.job}}
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: print a variable
        env:
          MY_JOB_STEP_ENV_VAR: ${{github.run_id}}
        run: |
          echo "this is global env variable : $MY_GLOBAL_ENV_VAR"
          echo "this is job env variable : $MY_JOB_ENV_VAR"
          echo "this is step env variable : $MY_JOB_STEP_ENV_VAR"
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
  debug-message:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger an error
        run: echo "::debug::Set the Octocat variable"
  error-message:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger an error
        run: echo "::error file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
  if-Windows-else:
    runs-on: macos-latest
    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
  modify-global-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Print original global env var
        run: echo "The original global env variable is $MY_GLOBAL_ENV_VAR"
      - name: Modify global env var
        run: echo "MY_GLOBAL_ENV_VAR=ModifiedValue" >> $GITHUB_ENV
      - name: Print modified global env var
        run: echo "The modified global env variable is $MY_GLOBAL_ENV_VAR"